# Generated by Django 5.1.4 on 2024-12-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NN', None), ('IPC', 'Image Processing')], default='NN')),
                ('is_active', models.BooleanField(default=False, verbose_name='Está Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('in_processing', models.FloatField(max_length=100, verbose_name='Em Processo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user', verbose_name='User ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.services', verbose_name='Service ID')),
            ],
        ),
    ]
