# Generated by Django 5.1.4 on 2024-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_services_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='in_processing',
        ),
        migrations.AddField(
            model_name='queue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Serviço Ativo?'),
        ),
        migrations.AddField(
            model_name='queue',
            name='progress_rate',
            field=models.FloatField(default=1, max_length=100, verbose_name='Progresso Atual'),
        ),
    ]
