# Generated by Django 5.1.4 on 2024-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_remove_queue_in_processing_queue_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(default='CPT', verbose_name='Status?'),
        ),
    ]
